[package]
name = "cambridge-asm-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1" }
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"

[dependencies.cambridge-asm]
version = "0.13"
default-features = false
