name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      with:
        node-version: 16.15.0

    - name: Install npm deps
      run: npm i -g typescript sass minify

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true
        target: wasm32-unknown-unknown
    
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build prod bundle
      run: sh prod.sh
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: prod
